### ISSUE TITLE
Proper stream type bitflags

### ISSUE THREAD

**Issue by yupferris** [RustAudio/coreaudio-rs#24]
Ran into issues with these implementing/testing a fix for #12. They need to be proper bitflags so they can be combined and all valid values can be represented.

**Comment by yupferris** [comment]
While this may also lead to some invalid combinations being represented, I don't think it's a problem as we're still guaranteed to be memory-safe, and the fact that we can propegate runtime errors covers that. I think that's more of an issue of the original API and one we shouldn't be too concerned about tackling, unless it ends up being pretty easy. Will have to see.

**Comment by mitchmindtree** [comment]
Ahh yep (I think I wrote this before I knew what bitflags were). There's a decent crate for bitflags [here](https://crates.io/crates/bitflags).

**Comment by mitchmindtree** [comment]
Going to look into fixing this now.

**Comment by yupferris** [comment]
awesome!

**Comment by yupferris** [comment]
Fixed in #27
